Modify jest workflow to see if I can trigger it

diff --git a/.github/workflows/jest.yml b/.github/workflows/jest.yml
--- a/.github/workflows/jest.yml
+++ b/.github/workflows/jest.yml
@@ -1,38 +1,15 @@
 name: Jest Tests
 on:
+  workflow_dispatch:
   workflow_run:
-    workflows: ["Build Boop", "build"]
+    workflows: [Build Boop]
     types:
       - completed
-  workflow_dispatch:
 
 jobs:
-  check-dependency:
-    name: Check Dependency
+  on-success:
     runs-on: ubuntu-latest
-    steps:
-      - name: Fail if not triggered by build workflow
-        if: github.event_name == 'workflow_dispatch' && github.event.workflow_run == null
-        run: |
-          echo "This workflow must be triggered by the 'Build React App' workflow."
-          echo "Manual runs are allowed only for debugging purposes when you're certain a successful build exists."
-          exit 1
-      
-      - name: Fail if build workflow failed
-        if: github.event.workflow_run != null && github.event.workflow_run.conclusion != 'success'
-        run: |
-          echo "The 'Build React App' workflow did not complete successfully."
-          echo "This workflow requires a successful build."
-          exit 1
-      
-      - name: Dependency check passed
-        run: echo "Dependency check passed, proceeding with tests."
-
-  test:
-    name: Run Jest Tests
-    runs-on: ubuntu-latest
-    needs: check-dependency
-
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v3
@@ -76,3 +53,9 @@ jobs:
           name: test_results
           path: test/.jest-test-results.json
           retention-days: 5
+  on-failure:
+    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    steps:
+      - run: echo 'The triggering workflow failed'
+      - run: exit 1
